services:
  kicau-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: kicau-frontend
    ports:
      - "3000:3004"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
